#version 450
#extension GL_ARB_shading_language_include : enable
#include <utils.glsl>
#include <brdf.glsl>

layout(binding = 0) uniform samplerCube skybox;
layout(r11f_g11f_b10f, binding = 1) writeonly uniform imageCube specularIbl;
layout(binding = 2) uniform Setup {
    float Roughness;
};

vec3 prefilterEnvironment(vec3 R, float roughness)
{
    vec3 N = normalize(R);
    vec3 V = N;

    if (roughness <= 0.0)
        return textureLod(skybox, N, 0.0).rgb * 3;

    vec3 sum = vec3(0.0);
    float totalWeight = 0.0;

    const uint SAMPLE_COUNT = 1024u;
    for (uint i = 0u; i < SAMPLE_COUNT; ++i) {
        vec2 xi = vec2(
            float(i) / float(SAMPLE_COUNT),
            radicalInverse(i)
        );

        vec3 H = importanceSampleBeckmann(xi, N, roughness);
        vec3 L = normalize(2.0 * dot(V, H) * H - V);

        float NoL = max(dot(N, L), 0.0);
        if (NoL > 0.0) {
            sum += textureLod(skybox, L, 0.0).rgb * NoL * 3;
            totalWeight += NoL;
        }
    }

    return sum / max(totalWeight, 1e-6);
}

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
void main() {
    ivec3 texelCoord = ivec3(gl_GlobalInvocationID.xyz);
    ivec2 size = imageSize(specularIbl);

    if (any(greaterThanEqual(texelCoord.xy, size)))
        return;

    vec3 R = cubeTexelDirection(texelCoord.z, texelCoord.xy, size.x);

    vec3 result = prefilterEnvironment(R, Roughness);
    imageStore(specularIbl, texelCoord, vec4(result, 0));
}
