#version 450
#extension GL_ARB_shading_language_include : enable
#include <utils.glsl>

layout(binding = 0) uniform samplerCube skybox;
layout(r11f_g11f_b10f, binding = 1) writeonly uniform imageCube diffuseIbl;

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
void main() {
    ivec3 texelCoord = ivec3(gl_GlobalInvocationID.xyz);
    ivec2 size = imageSize(diffuseIbl);

    if (any(greaterThanEqual(texelCoord.xy, size)))
        return;

    vec3 N = cubeTexelDirection(texelCoord.z, texelCoord.xy, size.x);

    vec3 helper = abs(N.z) < 0.999
            ? vec3(0.0, 0.0, 1.0)
            : vec3(0.0, 1.0, 0.0);

    vec3 T = normalize(cross(helper, N));
    vec3 B = cross(N, T);

    vec3 sum = vec3(0.0);
    const uint sampleCount = 512u;

    for (uint i = 0u; i < sampleCount; ++i) {
        vec2 xi = vec2(
            (float(i) + 0.5) / float(sampleCount),
            radicalInverse(i)
        );

        float r = sqrt(xi.x);
        float phi = 2.0 * PI * xi.y;

        vec3 localDir = vec3(
            r * cos(phi),
            r * sin(phi),
            sqrt(1.0 - xi.x)
        );

        vec3 direction =
            T * localDir.x +
            B * localDir.y +
            N * localDir.z;

        sum += textureLod(skybox, direction, 0.0).rgb * 2;
    }

    vec3 result = sum / float(sampleCount);

    imageStore(diffuseIbl, texelCoord, vec4(result, 0));
}