#version 450

layout(binding = 0) uniform LightsData {

    mat4 DirShadowViewPorjection;
    vec4 DirLightDirection;
    vec4 DirLightColor;
    float DepthBias;

} Lights;

layout(r11f_g11f_b10f, set = 0, binding = 1) writeonly uniform imageCube outCubemap; 

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
void main() {
    ivec3 texelCord = ivec3(gl_GlobalInvocationID.xyz);
    vec3 color = vec3(1.0, 0.0, 0.0);



    imageStore(outCubemap, texelCord, vec4(color, 0));
}