#version 450
#extension GL_ARB_shading_language_include : enable
#include <commonData.glsl>
#include <utils.glsl>

layout(binding = 0) uniform samplerCube skybox_raw;
layout(r11f_g11f_b10f, set = 0, binding = 1) writeonly uniform imageCube outCubemap;

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
void main() {

    ivec3 texelCord = ivec3(gl_GlobalInvocationID.xyz);
    ivec2 size = imageSize(outCubemap);

    if (any(greaterThanEqual(texelCord.xy, size)))
        return;

    vec3 wsDir = cubeTexelDirection(texelCord.z, texelCord.xy, size.x);

    vec4 color = textureLod(skybox_raw, wsDir.xzy, 0.0);

    imageStore(outCubemap, texelCord, color);
}